refactor: improve process logging

diff --git a/bin/start-nginx-debug b/bin/start-nginx-debug
--- a/bin/start-nginx-debug
+++ b/bin/start-nginx-debug
@@ -26,24 +26,26 @@ mkdir -p logs/nginx
 touch logs/nginx/access.log logs/nginx/error.log
 echo 'buildpack=nginx at=logs-initialized'
 
-# Start server.
+# Start app server.
 (
   # Take the command passed to this bin and start it.
   # E.g. bin/start-nginx bundle exec unicorn -c config/unicorn.rb
   COMMAND=${@:$n}
-  echo "buildpack=nginx at=start-app cmd=$COMMAND"
-  $COMMAND
-  echo 'Server terminated!'
+  echo "buildpack=nginx at=app-start cmd=$COMMAND"
+  $COMMAND \
+   & wait
+  echo 'buildpack=nginx at=app-terminated'
 ) &
-process_list[server]=$!
+process_list[$!]='app'
 
 # Start log redirection.
 (
   # Redirect nginx logs to stdout.
-  tail -qF -n 0 --pid=${process_list[server]} logs/nginx/*.log
-  echo 'Tail terminated!'
+  tail -qF -n 0 --pid=$! logs/nginx/*.log \
+   & wait
+  echo 'buildpack=nginx at=logs-terminated'
 ) &
-process_list[tail]=$!
+process_list[$!]='logs'
 
 if [[ -z "$FORCE" ]]
 then
@@ -64,11 +66,21 @@ fi
   # We expect nginx to run in foreground.
   # We also expect a socket to be at /tmp/nginx.socket.
   echo 'buildpack=nginx at=nginx-start'
-  bin/nginx-debug -p . -c config/nginx.conf
-  echo 'Nginx terminated!'
+  bin/nginx-debug -p . -c config/nginx.conf \
+   & wait
+  echo 'buildpack=nginx at=nginx-terminated'
 ) &
-process_list[nginx]=$!
+process_list[$!]='nginx'
 
-# Wait for everything to finish before exiting.
-wait "${process_list[@]}"
+# Iterate over processes and log their exit status.
+for process in "${!process_list[@]}"
+  do
+    # If we have bash 5.1 then we can use "wait -np JOB_ID" to find which
+    # job has finished, the value is put in $JOB_ID variable.
+    wait -np JOB_ID
+    echo "Process [${process_list[$JOB_ID]}] with id=$JOB_ID exited with RC=$?"
+    sleep 1
+  done
+
+# Bye.
 echo 'Bye!'
